# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd8d2d22a3d73a4c007ee87c24d5dd44e2084fc49b68f6331def1de64c4492492d9b5e7d53df3812f574a9426d3ed8fc258debce451be4423566d0cf82c1c837

test:
  secret_key_base: 32bedfdff28f6df5af47cfd212ba48bf0896ede3dcfc544447801f8970c3d431b5976f342a6c2a7e8cdd290fe88df6b92f22caf3f7f7632b778e6039da439423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
