# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.destroy_all
Product.destroy_all

Category.create([
  {name: "Electronics", img_url: "electronics.png", description: "televisions, phones, speakers, headphones"},
  {name: "Clothing", img_url: "clothing.png", description: "shirts, pants, skirts, outerwear, accessories"},
  {name: "Shoes, Belts, and Accessories", img_url: "shoes.png", description: "men's and women's shoes, belts, watches, jewelrey, bags"},
  {name: "Home and Outdoors", img_url: "home.png", description: "furniture, appliances, decorations, lights, outdoor"},
  {name: "Media", img_url: "media.png", description: "movies, games, books, music"},
  {name: "Sports", img_url: "sports.png", description: "training gear, equipment, balls, sports apparel"},
  {name: "Miscellaneous", img_url: "miscellaneous.png", description: "Miscellaneous products, services, and offers"}
])

Product.create([
  {name: "iPhone 7", price: 599.99, img_url: "iphone_7.png", description: "Apple iPhone 7 with retina display, 5mp camera, touch ID"},
  {name: "Polo Shirt", price: 34.99, img_url: "polo_shirt_1.png", description: "Polo Ralph Lauren button down shirt in light blue, size Large."},
  {name: "Carrana Lorena Leather Sandal", price: 79.99, img_url: "carrana_lorena_shoe.gif", description: "Make the night with these platform sandals. The juxtaposition of the snake skin golden pattern vamp and the soft black leather ankle strap and counter make this sandal a must have. "},
  {name: "Men's White/Gold Fossil Watch", price: 115.99, img_url: "fossil_watch.jpg", description: "Men's Fossil watch with white face, brown leather strap with gold metal frame and accents"},
  {name: "IKEA Couch", price: 399.99, img_url: "ikea_couch_1.jpg", description: "Multi-piece IKEA couch in black leather with hidden storage"},
  {name: "Star Wars: The Force Awakens", price: 19.99, img_url: "star_wars_episode_7.png", description: "Star Wars Episode VII: The Force Awakens on Blu-Ray HD"},
  {name: "Nike Soccer Ball", price: 15.99, img_url: "soccer_ball.png", description: "Nike Soccer Ball in grey, standard size"},
  {name: "Samsung Galaxy S7", price: 499.99, img_url:"samsung_galaxy_7.png", description: "The Samsung Galaxy S7 unlocks a Galaxy of technology that takes your smartphone experience to a new level. The bigger, more stunning screen completes the slimmer design.* Why not have a phone that’s water resistant, too? Galaxy S7 withstands splashes, spills and even dunks."},
  {name: 'LG 55" 4K HDTV', price: 899.99, img_url:"lg_tv.png", description: 'View content at four times the resolution of 1080p with the LG UH6150-Series 55"-Class UHD Smart IPS LED TV. Lower resolution video sources can also be upscaled to near-4K quality. This TV has a 54.6" LED-backlit IPS LCD display and incorporates TruMotion 120 Hz technology to digitally enhance fast-moving images to reduce blur.'},
  {name: "13-inch MacBook Pro", price: 1119.99, img_url:"macbook_pro.png", description: "The 13‑inch MacBook Pro with Retina display features Intel Iris Graphics 6100 to handle both everyday tasks and graphics-intensive creative apps. Scroll through large photo albums with ease. Play games with amazing detail. Even connect an external display or two."},
  {name: "Beats Solo 2 Wireless", price: 399.99, img_url:"beats.png", description: "Immerse yourself in the dazzling sound experience of the Beats Solo2. With a wider and more dynamic sound range for a better overall sound clarity. Use the included RemoteTalk(TM) cable to change songs, adjust volume and even take calls without reaching for your device."},
  {name: "Bose Bluetooth Speaker", price: 299.99, img_url:"bose_speakers.png", description: "The SoundLink Mini Bluetooth speaker II delivers full, natural sound with dramatically deeper bass than you’d expect from an ultra-compact speaker. Also features built-in microphone for taking calls and accessing Siri or Google Now"},
  {name: "Playstation 4", price: 499.99, img_url:"ps4.png", description: "The PlayStation 4 system provides dynamic, connected gaming, powerful graphics and speed, intelligent personalization, deeply integrated social capabilities, and innovative second-screen features."},
  {name: "XBox One", price: 399.99, img_url:"xbox_one.png", description: "Jump ahead with Xbox One. Where the best games, multiplayer, and your favorite movies, music, sports, and live TV come together in one place."},
  {name: "H&M Men's All-Weather Coat", price: 169.99, img_url:"hm_jacket.jpeg", description: "Technical outerwear features in a clean, uncompromising around-town winter coat that allows you to commute in comfort through wild weather of all sorts."},
  {name: "IHome Hover Alarm Clock", price: 85.99, img_url:"ihome.png", description: "The iDL46 is a hotel Mode Dual Charging Stereo FM Clock Radio with Lightning Dock and USB Charge/Play for iPad/iPhone/iPod. With the auto sync feature, syncing your iPhone time to the clock in moments and iHome Apps available, the iDL46 is the ideal guest friendly Alarm Clock Radio."},
  {name: "Dickies Slim Khakis", price: 24.99, img_url:"khakis.jpg", description: "Dickies 5-pocket Skinny Pant in Natural for Men, size 32"},
  {name: "Men's Vineyard Vines Belt", price: 18.99, img_url:"vv_belt.jpg", description: "A classic, beloved standard now uniquely re-engineered by Southern Tide, size 32"},
  {name: "Men's Nike Alabama Jersey", price: 83.99, img_url:"alabama_jersey.jpeg", description: "This is the perfect jersey for any fan looking to bulk up their collection of Alabama Crimson Tide player-inspired gear. It features your favorite player's name in his college colors."},
  {name: "Men's Nike Darwin Running Shoes", price: 49.99, img_url:"nike_shoes.jpg", description: "A fresh look brought together by two of Nike's favorites, the Nike Darwin is this year's newest minimalist sneaker."},
  {name: "Kate Spade Emerson Purse", price: 398.99, img_url:"kate_spade_purse.jpeg", description: "looking for a go-anywhere, carry-everything bag that's anything but basic? check out our new emerson place dewy, a roomy zip-top purse made from luxe quilted leather and finished with shiny golden hardware."},
  {name: "H&M Women's Blouse", price: 29.99, img_url:"hm_blouse.jpeg", description: "Wide-cut, V-neck blouse in satin. Concealed buttons at front, long sleeves with ruffle and button at cuffs, and decorative gathers at shoulders and back."},
  {name: "Yves Saint Laurent Men's Scarf", price: 69.99, img_url:"ysl_scarf.png", description: "Cashmere fringed scarf with signature logo embroidery"},
  {name: "Apt. 9 Men's Square-Toe Dress Shoes", price: 39.99, img_url:"apt9_shoes.jpeg", description: "Rise to the occasion with confidence in these men's square-toe dress shoes from Apt. 9, size 11.5"},
  {name: "Grey Nike Women's Running Pants", price: 39.99, img_url:"nike_womens_pants.jpg", description: "The Nike All Time Update Women's Training Pants are designed with brushed Therma-FIT fleece and inseam panels for insulated comfort and increased range of motion during outdoor training."},
  {name: "Tommy Hilfiger Tie", price: 22.99, img_url:"tommy_tie.jpeg", description: "Perfect for the pattern shy. Sleek suiting requires a slim silk tie from Tommy Hilfiger."},
  {name: "IKEA Dudero Floor Lamp", price: 34.99, img_url:"ikea_lamp.jpeg", description: "Rice paper, gives a soft mood light"},
  {name: "4 X 6 Heriz Serapi Oriental Rug", price: 79.99, img_url:"persian_rug.jpg", description: "This Is a True Hand Knotted Oriental Rug. It Is Not Hand Tufted with Backing, Not Hooked or Machine Made"},
  {name: "Round Seat Bar/ Counter Height Adjustable Metal Bar Stool", price: 40.99, img_url:"barstool.jpg", description: "Infuse your home with the sleek, modern styling of this Round Seat Bar/ Counter Height Adjustable Metal Bar Stool. The contemporary design complements with modern or traditional decor. Crafted from strong metal, this stool showcases a rich, powder-coated antique brown finished paired with a microfiber plush foam seat for comfort."},
  {name: "Cheer Collection Faux Fur to Microplush Reversible Throw Blanket", price: 32.99, img_url:"throw_blanket.jpg", description: "Perfect for adding texture to your space, these faux fur throws look warm and inviting, calling you to curl up right next to them. These classic throws add style to any room and are machine-washable for conveniently easy care."},
  {name: "Grain Wood Furniture Loft Solid Wood Queen-size Panel Platform Bed", price: 499.99, img_url:"bed.jpg", description: "Bring taste and charm to any bedroom with this stunning panel platform bed. Crafted from solid pine with a beautifully weathered finish, this gorgeous bed is built to last, promising style and comfort for years to come."},
  {name: "New Era Cap Atlanta Falcons Historic Cap", price: 28.99, img_url: "falcons_hat.jpg", description: "Atlanta Falcons Historic The Team Flip 2 A-Frame SNAPBACK"},
  {name: "Highwood Synthetic Wood Lehigh Rocking Chair", price: 39.99, img_url: "rocking_chair.jpg", description: "Enjoy the outdoor world with indoor comfort on this environmentally friendly rocking chair. Its simple yet elegant design is well-suited for any porch, patio or backyard. Select from eight unique color choices to match your outdoor decor."},
  {name: "Battlefield One - PS4", price: 59.99, img_url: "battlefield_one.jpg", description: "Take the battle from the scenic Italian coast to the scorching Arabian deserts. Discover classic Battlefield gameplay through an adventure-filled campaign, or squad up and join epic multiplayer battles with up to 64 players."},
  {name: "Outliers : The Story of Success", price: 15.99, img_url: "outliers.png", description: "In this stunning new book, Malcolm Gladwell takes us on an intellectual journey through the world of 'outliers'--the best and the brightest, the most famous and the most successful. He asks the question: what makes high-achievers different?"},
  {name: "Freakonomics : A Rogue Economist Explores the Hidden Side of Everything", price: 14.99, img_url: "freakonomics.jpg", description: "Steven D. Levitt and Stephen J. Dubner offer the long-awaited paperback edition ofFreakonomics, the runaway bestseller, including six Freakonomics columns from theNew York Times Magazine and a Q & A with the authors."},
  {name: "Microsoft Office Home & Student 2016 for Mac", price: 118.99, img_url: "ms_office_mac.png", description: "Microsoft Office Home and Student 2016 for Mac gets you working at your best on the critical everyday computing tasks. With new improvements such as ink annotations, which allow you to make annotations to help clarify points of emphasis on all of your work for your viewing audience, your Word documents and Excel spreadsheets come to life and carry your own personal style. "},
  {name: "Google Chromecast 2", price: 35.99, img_url: "chromecast.jpg", description: "Chromecast is a media streaming device that plugs into the HDMI port on your TV. Simply use your mobile device and the TV you already own to cast your favorite TV shows, movies, music, sports, games and more."},
  {name: "Game Of Thrones: The Complete Fifth Season", price: 59.99, img_url: "game_of_thrones.jpeg", description: "Game Of Thrones returns for a fifth season where a plethora of compelling storylines play out to their inevitable, often bloody conclusions. "},
  {name: "Star Trek Beyond - DVD", price: 18.76, img_url: "star_trek_beyond.jpeg", description: "Star Trek Beyond, the highly anticipated next installment in the globally popular Star Trek franchise, created by Gene Roddenberry and reintroduced by J.J. Abrams in 2009, returns with director Justin Lin at the helm of this epic voyage of the U.S.S. Enterprise and her intrepid crew."},
  {name: "Destiny: The Taken King - Legendary Edition", price: 59.99, img_url: "destiny.jpeg", description: "n Destiny: The Taken King, the Darkness has a name: Oryx, The Taken King. He is hell-bent on vengeance and is raising an army of corrupted Taken forces to destroy everything you stand for. You must find a way into his impenetrable Dreadnaught ship and stop him before he and his dark army bring our solar system to ruin"},
  {name: "Nike Men's Alpha Shark 2 Cleats", price: 49.99, img_url: "nike_cleats.jpg", description: "Tear through the competition in the Alpha Shark II. Lightweight synthetic leather upper delivers unbeatable performance, durability and a locked in fit while a full-length Phylon midsole provides responsive cushioning for added comfort"},
  {name: "Washington Wizards vs. New York Knicks", price: 89.99, img_url: "wizards.png", description: "Washington Wizards vs. New York Knicks - Verizon Center - March 8, 2017"},
  {name: "Full-Face Helmet", price: 45.99, img_url: "motorcycle_helmet.jpeg", description: "The Full-Face Helmet offers a durable, reliable and efficient method for protecting and securing the head during motorcycling or other sporting activities."},
  {name: "Tufted Pet Bed, Brown/Cream", price: 12.99, img_url: "dog_bed.jpeg", description: "This 27-inch by 36-inch Tufted Pet Bed features plush fabrics with decorative corner patches. It's filled with 100 percent recycled polyester fiberfill. This pet bed is machine-washable for easy care."},
  {name: "Men's Remington Hair Trimmer", price: 52.99, img_url: "trimmer.jpeg", description: "This is one tough cutter. The Remington Cordless Virtually Indestructible Cordless Haircut Kit is built to last, featuring a high-impact casing that protects the powerful interior."},
  {name: "$50 Best Buy Gift Card", price: 44.99, img_url: "bestbuy_card.jpg", description: "Skip the holiday lines this year and give everyone on your list the chance to choose their perfect gift with Best Buy holiday gift cards."},
])

CategoryTag.create([
  {product_id: 1, category_id: 1},
  {product_id: 2, category_id: 2},
  {product_id: 3, category_id: 3},
  {product_id: 4, category_id: 3},
  {product_id: 5, category_id: 4},
  {product_id: 6, category_id: 5},
  {product_id: 7, category_id: 6},
  {product_id: 8, category_id: 1},
  {product_id: 9, category_id: 1},
  {product_id: 10, category_id: 1},
  {product_id: 11, category_id: 1},
  {product_id: 12, category_id: 1},
  {product_id: 13, category_id: 1},
  {product_id: 14, category_id: 1},
  {product_id: 15, category_id: 2},
  {product_id: 16, category_id: 1},
  {product_id: 16, category_id: 4},
  {product_id: 17, category_id: 2},
  {product_id: 18, category_id: 3},
  {product_id: 19, category_id: 2},
  {product_id: 19, category_id: 6},
  {product_id: 20, category_id: 3},
  {product_id: 20, category_id: 6},
  {product_id: 21, category_id: 3},
  {product_id: 22, category_id: 2},
  {product_id: 23, category_id: 2},
  {product_id: 23, category_id: 3},
  {product_id: 24, category_id: 3},
  {product_id: 25, category_id: 2},
  {product_id: 25, category_id: 6},
  {product_id: 26, category_id: 2},
  {product_id: 26, category_id: 3},
  {product_id: 27, category_id: 4},
  {product_id: 28, category_id: 4},
  {product_id: 29, category_id: 4},
  {product_id: 30, category_id: 4},
  {product_id: 31, category_id: 4},
  {product_id: 32, category_id: 3},
  {product_id: 32, category_id: 6},
  {product_id: 33, category_id: 4},
  {product_id: 34, category_id: 5},
  {product_id: 35, category_id: 5},
  {product_id: 36, category_id: 5},
  {product_id: 37, category_id: 5},
  {product_id: 38, category_id: 1},
  {product_id: 38, category_id: 5},
  {product_id: 39, category_id: 5},
  {product_id: 40, category_id: 5},
  {product_id: 41, category_id: 5},
  {product_id: 42, category_id: 6},
  {product_id: 43, category_id: 7},
  {product_id: 44, category_id: 7},
  {product_id: 45, category_id: 7},
  {product_id: 46, category_id: 7},
  {product_id: 47, category_id: 7},
])
